[package]
name = "merthc"
version = "0.1.0"
authors = ["Peter Marheine <peter@taricorp.net>"]
build = "build.rs"

[dependencies]
llvm-sys = "0.2"
libc = "0.2"
phf = "0.7"

[build-dependencies]
phf_codegen = "0.7"
